[package]
name = "hatchet-sdk"
description = "Rust SDK for Hatchet"
authors = ["Ethan Wolinsky"]
license = "MIT OR Apache-2.0"
version = "0.1.0-alpha.1"
edition = "2024"

[features]
client = []
worker = []

[dependencies]
tonic = { version = "0.13", features = [
    "channel",
    "_tls-any",
    "tls-native-roots",
] }
prost = "*"
tokio = "*"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.22"
prost-types = "*"
reqwest = { version = "^0.12.22", features = ["json"] }

[build-dependencies]
tonic-build = "*"

[dev-dependencies]
dotenvy = "*"
