[package]
name = "hatchet-sdk"
description = "Rust SDK for Hatchet"
authors = ["Ethan Wolinsky"]
license = "MIT OR Apache-2.0"
version = "0.1.0-alpha.2"
edition = "2024"

[features]
client = []
worker = []

[dependencies]
tonic = { version = "0.13", features = [
    "channel",
    "_tls-any",
    "tls-native-roots",
] }
base64 = "0.22"
prost = "0.13"
prost-types = "0.13"
reqwest = { version = "0.12.22", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = "1.46.1"
thiserror = "2"
tokio-stream = "0.1.17"
tokio-util = "0.7.15"
async-trait = "0.1.88"
futures = "0.3.31"
dyn-clone = "1.0.20"

[build-dependencies]
tonic-build = { version = "0.13.1", features = ["prost"] }

[dev-dependencies]
dotenvy = "0.15.7"
mockall = "0.13"
rstest = "0.26.1"
