[package]
name = "hatchet-rust-sdk"
version = "0.1.0"
edition = "2024"

[features]
client = []
worker = []

[dependencies]
tonic = "*"
prost = "*"
tokio = "*"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.22"

[build-dependencies]
tonic-build = "*"

[dev-dependencies]
dotenvy = "*"
