/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AlertEmailGroupCreateRequest {
    /// A list of emails for users
    #[serde(rename = "emails")]
    pub emails: Vec<String>,
}

impl AlertEmailGroupCreateRequest {
    pub fn new(emails: Vec<String>) -> AlertEmailGroupCreateRequest {
        AlertEmailGroupCreateRequest { emails }
    }
}
