/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AlertEmailGroupList200ResponseRowsInner {
    #[serde(rename = "metadata")]
    pub metadata: Box<models::V1TaskGet200ResponseMetadata>,
    /// A list of emails for users
    #[serde(rename = "emails")]
    pub emails: Vec<String>,
}

impl AlertEmailGroupList200ResponseRowsInner {
    pub fn new(metadata: models::V1TaskGet200ResponseMetadata, emails: Vec<String>) -> AlertEmailGroupList200ResponseRowsInner {
        AlertEmailGroupList200ResponseRowsInner {
            metadata: Box::new(metadata),
            emails,
        }
    }
}

