/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiTokenList200ResponseRowsInner {
    #[serde(rename = "metadata")]
    pub metadata: Box<models::V1TaskGet200ResponseMetadata>,
    /// The name of the API token.
    #[serde(rename = "name")]
    pub name: String,
    /// When the API token expires.
    #[serde(rename = "expiresAt")]
    pub expires_at: String,
}

impl ApiTokenList200ResponseRowsInner {
    pub fn new(metadata: models::V1TaskGet200ResponseMetadata, name: String, expires_at: String) -> ApiTokenList200ResponseRowsInner {
        ApiTokenList200ResponseRowsInner {
            metadata: Box::new(metadata),
            name,
            expires_at,
        }
    }
}

