/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiTokenCreate200Response {
    /// The API token.
    #[serde(rename = "token")]
    pub token: String,
}

impl ApiTokenCreate200Response {
    pub fn new(token: String) -> ApiTokenCreate200Response {
        ApiTokenCreate200Response {
            token,
        }
    }
}

