/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiTokenCreateRequest {
    /// A name for the API token.
    #[serde(rename = "name")]
    pub name: String,
    /// The duration for which the token is valid.
    #[serde(rename = "expiresIn", skip_serializing_if = "Option::is_none")]
    pub expires_in: Option<String>,
}

impl ApiTokenCreateRequest {
    pub fn new(name: String) -> ApiTokenCreateRequest {
        ApiTokenCreateRequest {
            name,
            expires_in: None,
        }
    }
}
