/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CronWorkflowTriggerCreate200Response {
    #[serde(rename = "metadata")]
    pub metadata: Box<models::V1TaskGet200ResponseMetadata>,
    #[serde(rename = "tenantId")]
    pub tenant_id: String,
    #[serde(rename = "workflowVersionId")]
    pub workflow_version_id: String,
    #[serde(rename = "workflowId")]
    pub workflow_id: String,
    #[serde(rename = "workflowName")]
    pub workflow_name: String,
    #[serde(rename = "cron")]
    pub cron: String,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "input", skip_serializing_if = "Option::is_none")]
    pub input: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "additionalMetadata", skip_serializing_if = "Option::is_none")]
    pub additional_metadata: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "method")]
    pub method: Method,
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<i32>,
}

impl CronWorkflowTriggerCreate200Response {
    pub fn new(metadata: models::V1TaskGet200ResponseMetadata, tenant_id: String, workflow_version_id: String, workflow_id: String, workflow_name: String, cron: String, enabled: bool, method: Method) -> CronWorkflowTriggerCreate200Response {
        CronWorkflowTriggerCreate200Response {
            metadata: Box::new(metadata),
            tenant_id,
            workflow_version_id,
            workflow_id,
            workflow_name,
            cron,
            name: None,
            input: None,
            additional_metadata: None,
            enabled,
            method,
            priority: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Method {
    #[serde(rename = "DEFAULT")]
    Default,
    #[serde(rename = "API")]
    Api,
}

impl Default for Method {
    fn default() -> Method {
        Self::Default
    }
}

