/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventUpdateCancel200Response {
    #[serde(rename = "workflowRunIds", skip_serializing_if = "Option::is_none")]
    pub workflow_run_ids: Option<Vec<uuid::Uuid>>,
}

impl EventUpdateCancel200Response {
    pub fn new() -> EventUpdateCancel200Response {
        EventUpdateCancel200Response {
            workflow_run_ids: None,
        }
    }
}
