/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventUpdateReplayRequest {
    #[serde(rename = "eventIds")]
    pub event_ids: Vec<uuid::Uuid>,
}

impl EventUpdateReplayRequest {
    pub fn new(event_ids: Vec<uuid::Uuid>) -> EventUpdateReplayRequest {
        EventUpdateReplayRequest {
            event_ids,
        }
    }
}

