/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventDataGet200Response {
    /// The data for the event (JSON bytes).
    #[serde(rename = "data")]
    pub data: String,
}

impl EventDataGet200Response {
    pub fn new(data: String) -> EventDataGet200Response {
        EventDataGet200Response { data }
    }
}
