/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LogLineList200ResponseRowsInner {
    /// The creation date of the log line.
    #[serde(rename = "createdAt")]
    pub created_at: String,
    /// The log message.
    #[serde(rename = "message")]
    pub message: String,
    /// The log metadata.
    #[serde(rename = "metadata")]
    pub metadata: serde_json::Value,
}

impl LogLineList200ResponseRowsInner {
    pub fn new(
        created_at: String,
        message: String,
        metadata: serde_json::Value,
    ) -> LogLineList200ResponseRowsInner {
        LogLineList200ResponseRowsInner {
            created_at,
            message,
            metadata,
        }
    }
}
