/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MetadataGet200ResponseAuth {
    /// the supported types of authentication
    #[serde(rename = "schemes", skip_serializing_if = "Option::is_none")]
    pub schemes: Option<Vec<String>>,
}

impl MetadataGet200ResponseAuth {
    pub fn new() -> MetadataGet200ResponseAuth {
        MetadataGet200ResponseAuth {
            schemes: None,
        }
    }
}

