/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MetadataListIntegrations200ResponseInner {
    /// the name of the integration
    #[serde(rename = "name")]
    pub name: String,
    /// whether this integration is enabled on the instance
    #[serde(rename = "enabled")]
    pub enabled: bool,
}

impl MetadataListIntegrations200ResponseInner {
    pub fn new(name: String, enabled: bool) -> MetadataListIntegrations200ResponseInner {
        MetadataListIntegrations200ResponseInner {
            name,
            enabled,
        }
    }
}

