/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MetadataGet200ResponsePosthog {
    /// the PostHog API key
    #[serde(rename = "apiKey", skip_serializing_if = "Option::is_none")]
    pub api_key: Option<String>,
    /// the PostHog API host
    #[serde(rename = "apiHost", skip_serializing_if = "Option::is_none")]
    pub api_host: Option<String>,
}

impl MetadataGet200ResponsePosthog {
    pub fn new() -> MetadataGet200ResponsePosthog {
        MetadataGet200ResponsePosthog {
            api_key: None,
            api_host: None,
        }
    }
}
