/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScheduledWorkflowRunCreateRequest {
    #[serde(rename = "input")]
    pub input: serde_json::Value,
    #[serde(rename = "additionalMetadata")]
    pub additional_metadata: serde_json::Value,
    #[serde(rename = "triggerAt")]
    pub trigger_at: String,
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<i32>,
}

impl ScheduledWorkflowRunCreateRequest {
    pub fn new(input: serde_json::Value, additional_metadata: serde_json::Value, trigger_at: String) -> ScheduledWorkflowRunCreateRequest {
        ScheduledWorkflowRunCreateRequest {
            input,
            additional_metadata,
            trigger_at,
            priority: None,
        }
    }
}

