/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StepRunUpdateRerunRequest {
    #[serde(rename = "input")]
    pub input: serde_json::Value,
}

impl StepRunUpdateRerunRequest {
    pub fn new(input: serde_json::Value) -> StepRunUpdateRerunRequest {
        StepRunUpdateRerunRequest { input }
    }
}
