/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TenantGetQueueMetrics200ResponseWorkflowValue {
    /// The number of items in the queue.
    #[serde(rename = "numQueued")]
    pub num_queued: i32,
    /// The number of items running.
    #[serde(rename = "numRunning")]
    pub num_running: i32,
    /// The number of items pending.
    #[serde(rename = "numPending")]
    pub num_pending: i32,
}

impl TenantGetQueueMetrics200ResponseWorkflowValue {
    pub fn new(num_queued: i32, num_running: i32, num_pending: i32) -> TenantGetQueueMetrics200ResponseWorkflowValue {
        TenantGetQueueMetrics200ResponseWorkflowValue {
            num_queued,
            num_running,
            num_pending,
        }
    }
}

