/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TenantResourcePolicyGet200Response {
    /// A list of resource limits for the tenant.
    #[serde(rename = "limits")]
    pub limits: Vec<models::TenantResourcePolicyGet200ResponseLimitsInner>,
}

impl TenantResourcePolicyGet200Response {
    pub fn new(
        limits: Vec<models::TenantResourcePolicyGet200ResponseLimitsInner>,
    ) -> TenantResourcePolicyGet200Response {
        TenantResourcePolicyGet200Response { limits }
    }
}
