/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

/// TenantGetQueueMetrics200ResponseTotal : The total queue metrics.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TenantGetQueueMetrics200ResponseTotal {
    /// The number of items in the queue.
    #[serde(rename = "numQueued")]
    pub num_queued: i32,
    /// The number of items running.
    #[serde(rename = "numRunning")]
    pub num_running: i32,
    /// The number of items pending.
    #[serde(rename = "numPending")]
    pub num_pending: i32,
}

impl TenantGetQueueMetrics200ResponseTotal {
    /// The total queue metrics.
    pub fn new(
        num_queued: i32,
        num_running: i32,
        num_pending: i32,
    ) -> TenantGetQueueMetrics200ResponseTotal {
        TenantGetQueueMetrics200ResponseTotal {
            num_queued,
            num_running,
            num_pending,
        }
    }
}
