/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TenantGetStepRunQueueMetrics200Response {
    #[serde(rename = "queues", skip_serializing_if = "Option::is_none")]
    pub queues: Option<serde_json::Value>,
}

impl TenantGetStepRunQueueMetrics200Response {
    pub fn new() -> TenantGetStepRunQueueMetrics200Response {
        TenantGetStepRunQueueMetrics200Response {
            queues: None,
        }
    }
}

