/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TenantInviteAcceptRequest {
    #[serde(rename = "invite")]
    pub invite: String,
}

impl TenantInviteAcceptRequest {
    pub fn new(invite: String) -> TenantInviteAcceptRequest {
        TenantInviteAcceptRequest {
            invite,
        }
    }
}

