/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserUpdateLoginRequest {
    /// The email address of the user.
    #[serde(rename = "email")]
    pub email: String,
    /// The password of the user.
    #[serde(rename = "password")]
    pub password: String,
}

impl UserUpdateLoginRequest {
    pub fn new(email: String, password: String) -> UserUpdateLoginRequest {
        UserUpdateLoginRequest { email, password }
    }
}
