/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserCreateRequest {
    /// The name of the user.
    #[serde(rename = "name")]
    pub name: String,
    /// The email address of the user.
    #[serde(rename = "email")]
    pub email: String,
    /// The password of the user.
    #[serde(rename = "password")]
    pub password: String,
}

impl UserCreateRequest {
    pub fn new(name: String, email: String, password: String) -> UserCreateRequest {
        UserCreateRequest {
            name,
            email,
            password,
        }
    }
}

