/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserUpdatePasswordRequest {
    /// The password of the user.
    #[serde(rename = "password")]
    pub password: String,
    /// The new password for the user.
    #[serde(rename = "newPassword")]
    pub new_password: String,
}

impl UserUpdatePasswordRequest {
    pub fn new(password: String, new_password: String) -> UserUpdatePasswordRequest {
        UserUpdatePasswordRequest {
            password,
            new_password,
        }
    }
}

