/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1DagListTasks200ResponseInner {
    #[serde(rename = "dagId", skip_serializing_if = "Option::is_none")]
    pub dag_id: Option<uuid::Uuid>,
    #[serde(rename = "children", skip_serializing_if = "Option::is_none")]
    pub children: Option<Vec<models::V1TaskGet200ResponseChildrenInnerChildrenInner>>,
}

impl V1DagListTasks200ResponseInner {
    pub fn new() -> V1DagListTasks200ResponseInner {
        V1DagListTasks200ResponseInner {
            dag_id: None,
            children: None,
        }
    }
}
