/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

/// V1EventList200ResponseRowsInnerWorkflowRunSummary : The workflow run summary for this event.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1EventList200ResponseRowsInnerWorkflowRunSummary {
    /// The number of running runs.
    #[serde(rename = "running")]
    pub running: i64,
    /// The number of queued runs.
    #[serde(rename = "queued")]
    pub queued: i64,
    /// The number of succeeded runs.
    #[serde(rename = "succeeded")]
    pub succeeded: i64,
    /// The number of failed runs.
    #[serde(rename = "failed")]
    pub failed: i64,
    /// The number of cancelled runs.
    #[serde(rename = "cancelled")]
    pub cancelled: i64,
}

impl V1EventList200ResponseRowsInnerWorkflowRunSummary {
    /// The workflow run summary for this event.
    pub fn new(
        running: i64,
        queued: i64,
        succeeded: i64,
        failed: i64,
        cancelled: i64,
    ) -> V1EventList200ResponseRowsInnerWorkflowRunSummary {
        V1EventList200ResponseRowsInnerWorkflowRunSummary {
            running,
            queued,
            succeeded,
            failed,
            cancelled,
        }
    }
}
