/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1EventList200ResponseRowsInnerTriggeredRunsInner {
    /// The external ID of the triggered run.
    #[serde(rename = "workflowRunId")]
    pub workflow_run_id: uuid::Uuid,
    /// The ID of the filter that triggered the run, if applicable.
    #[serde(rename = "filterId", skip_serializing_if = "Option::is_none")]
    pub filter_id: Option<uuid::Uuid>,
}

impl V1EventList200ResponseRowsInnerTriggeredRunsInner {
    pub fn new(workflow_run_id: uuid::Uuid) -> V1EventList200ResponseRowsInnerTriggeredRunsInner {
        V1EventList200ResponseRowsInnerTriggeredRunsInner {
            workflow_run_id,
            filter_id: None,
        }
    }
}

