/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1TaskGet200ResponseMetadata {
    /// the id of this resource, in UUID format
    #[serde(rename = "id")]
    pub id: String,
    /// the time that this resource was created
    #[serde(rename = "createdAt")]
    pub created_at: String,
    /// the time that this resource was last updated
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl V1TaskGet200ResponseMetadata {
    pub fn new(id: String, created_at: String, updated_at: String) -> V1TaskGet200ResponseMetadata {
        V1TaskGet200ResponseMetadata {
            id,
            created_at,
            updated_at,
        }
    }
}

