/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1TaskCancel200Response {
    /// The list of task external ids that were cancelled
    #[serde(rename = "ids", skip_serializing_if = "Option::is_none")]
    pub ids: Option<Vec<uuid::Uuid>>,
}

impl V1TaskCancel200Response {
    pub fn new() -> V1TaskCancel200Response {
        V1TaskCancel200Response {
            ids: None,
        }
    }
}

