/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1TaskGetPointMetrics200Response {
    #[serde(rename = "results", skip_serializing_if = "Option::is_none")]
    pub results: Option<Vec<models::V1TaskGetPointMetrics200ResponseResultsInner>>,
}

impl V1TaskGetPointMetrics200Response {
    pub fn new() -> V1TaskGetPointMetrics200Response {
        V1TaskGetPointMetrics200Response { results: None }
    }
}
