/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1TaskGet400Response {
    #[serde(rename = "errors")]
    pub errors: Vec<models::V1TaskGet400ResponseErrorsInner>,
}

impl V1TaskGet400Response {
    pub fn new(errors: Vec<models::V1TaskGet400ResponseErrorsInner>) -> V1TaskGet400Response {
        V1TaskGet400Response {
            errors,
        }
    }
}

