/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1WebhookCreateRequestOneOfAllOfAuth {
    /// The username for basic auth
    #[serde(rename = "username")]
    pub username: String,
    /// The password for basic auth
    #[serde(rename = "password")]
    pub password: String,
}

impl V1WebhookCreateRequestOneOfAllOfAuth {
    pub fn new(username: String, password: String) -> V1WebhookCreateRequestOneOfAllOfAuth {
        V1WebhookCreateRequestOneOfAllOfAuth {
            username,
            password,
        }
    }
}

