/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1WebhookCreateRequestOneOf1AllOfAuth {
    /// The name of the header to use for the API key
    #[serde(rename = "headerName")]
    pub header_name: String,
    /// The API key to use for authentication
    #[serde(rename = "apiKey")]
    pub api_key: String,
}

impl V1WebhookCreateRequestOneOf1AllOfAuth {
    pub fn new(header_name: String, api_key: String) -> V1WebhookCreateRequestOneOf1AllOfAuth {
        V1WebhookCreateRequestOneOf1AllOfAuth {
            header_name,
            api_key,
        }
    }
}
