/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1WorkflowRunDisplayNamesList200ResponseRowsInner {
    #[serde(rename = "metadata")]
    pub metadata: Box<models::V1TaskGet200ResponseMetadata>,
    #[serde(rename = "displayName")]
    pub display_name: String,
}

impl V1WorkflowRunDisplayNamesList200ResponseRowsInner {
    pub fn new(metadata: models::V1TaskGet200ResponseMetadata, display_name: String) -> V1WorkflowRunDisplayNamesList200ResponseRowsInner {
        V1WorkflowRunDisplayNamesList200ResponseRowsInner {
            metadata: Box::new(metadata),
            display_name,
        }
    }
}

