/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1WorkflowRunList200Response {
    #[serde(rename = "pagination")]
    pub pagination: Box<models::V1TaskEventList200ResponsePagination>,
    /// The list of tasks
    #[serde(rename = "rows")]
    pub rows: Vec<models::V1TaskGet200ResponseChildrenInnerChildrenInner>,
}

impl V1WorkflowRunList200Response {
    pub fn new(pagination: models::V1TaskEventList200ResponsePagination, rows: Vec<models::V1TaskGet200ResponseChildrenInnerChildrenInner>) -> V1WorkflowRunList200Response {
        V1WorkflowRunList200Response {
            pagination: Box::new(pagination),
            rows,
        }
    }
}

