/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1WebhookList200Response {
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<models::V1TaskEventList200ResponsePagination>>,
    #[serde(rename = "rows", skip_serializing_if = "Option::is_none")]
    pub rows: Option<Vec<models::V1WebhookList200ResponseRowsInner>>,
}

impl V1WebhookList200Response {
    pub fn new() -> V1WebhookList200Response {
        V1WebhookList200Response {
            pagination: None,
            rows: None,
        }
    }
}

