/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1WorkflowRunDisplayNamesList200Response {
    #[serde(rename = "pagination")]
    pub pagination: Box<models::V1TaskEventList200ResponsePagination>,
    /// The list of display names
    #[serde(rename = "rows")]
    pub rows: Vec<models::V1WorkflowRunDisplayNamesList200ResponseRowsInner>,
}

impl V1WorkflowRunDisplayNamesList200Response {
    pub fn new(
        pagination: models::V1TaskEventList200ResponsePagination,
        rows: Vec<models::V1WorkflowRunDisplayNamesList200ResponseRowsInner>,
    ) -> V1WorkflowRunDisplayNamesList200Response {
        V1WorkflowRunDisplayNamesList200Response {
            pagination: Box::new(pagination),
            rows,
        }
    }
}
