/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookCreate200Response {
    #[serde(rename = "metadata")]
    pub metadata: Box<models::V1TaskGet200ResponseMetadata>,
    /// The name of the webhook worker.
    #[serde(rename = "name")]
    pub name: String,
    /// The webhook url.
    #[serde(rename = "url")]
    pub url: String,
    /// The secret key for validation.
    #[serde(rename = "secret")]
    pub secret: String,
}

impl WebhookCreate200Response {
    pub fn new(metadata: models::V1TaskGet200ResponseMetadata, name: String, url: String, secret: String) -> WebhookCreate200Response {
        WebhookCreate200Response {
            metadata: Box::new(metadata),
            name,
            url,
            secret,
        }
    }
}

