/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookList200ResponseRowsInner {
    #[serde(rename = "metadata")]
    pub metadata: Box<models::V1TaskGet200ResponseMetadata>,
    /// The name of the webhook worker.
    #[serde(rename = "name")]
    pub name: String,
    /// The webhook url.
    #[serde(rename = "url")]
    pub url: String,
}

impl WebhookList200ResponseRowsInner {
    pub fn new(
        metadata: models::V1TaskGet200ResponseMetadata,
        name: String,
        url: String,
    ) -> WebhookList200ResponseRowsInner {
        WebhookList200ResponseRowsInner {
            metadata: Box::new(metadata),
            name,
            url,
        }
    }
}
