/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookRequestsList200Response {
    /// The list of webhook requests.
    #[serde(rename = "requests", skip_serializing_if = "Option::is_none")]
    pub requests: Option<Vec<models::WebhookRequestsList200ResponseRequestsInner>>,
}

impl WebhookRequestsList200Response {
    pub fn new() -> WebhookRequestsList200Response {
        WebhookRequestsList200Response { requests: None }
    }
}
