/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookCreateRequest {
    /// The name of the webhook worker.
    #[serde(rename = "name")]
    pub name: String,
    /// The webhook url.
    #[serde(rename = "url")]
    pub url: String,
    /// The secret key for validation. If not provided, a random secret will be generated.
    #[serde(rename = "secret", skip_serializing_if = "Option::is_none")]
    pub secret: Option<String>,
}

impl WebhookCreateRequest {
    pub fn new(name: String, url: String) -> WebhookCreateRequest {
        WebhookCreateRequest {
            name,
            url,
            secret: None,
        }
    }
}
