/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkflowList200ResponseRowsInnerVersionsInner {
    #[serde(rename = "metadata")]
    pub metadata: Box<models::V1TaskGet200ResponseMetadata>,
    /// The version of the workflow.
    #[serde(rename = "version")]
    pub version: String,
    #[serde(rename = "order")]
    pub order: i32,
    #[serde(rename = "workflowId")]
    pub workflow_id: String,
    #[serde(rename = "workflow", skip_serializing_if = "Option::is_none")]
    pub workflow: Option<serde_json::Value>,
}

impl WorkflowList200ResponseRowsInnerVersionsInner {
    pub fn new(metadata: models::V1TaskGet200ResponseMetadata, version: String, order: i32, workflow_id: String) -> WorkflowList200ResponseRowsInnerVersionsInner {
        WorkflowList200ResponseRowsInnerVersionsInner {
            metadata: Box::new(metadata),
            version,
            order,
            workflow_id,
            workflow: None,
        }
    }
}

