/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkflowVersionGet200Response {
    #[serde(rename = "metadata")]
    pub metadata: Box<models::V1TaskGet200ResponseMetadata>,
    /// The version of the workflow.
    #[serde(rename = "version")]
    pub version: String,
    #[serde(rename = "order")]
    pub order: i32,
    #[serde(rename = "workflowId")]
    pub workflow_id: String,
    /// The sticky strategy of the workflow.
    #[serde(rename = "sticky", skip_serializing_if = "Option::is_none")]
    pub sticky: Option<String>,
    /// The default priority of the workflow.
    #[serde(rename = "defaultPriority", skip_serializing_if = "Option::is_none")]
    pub default_priority: Option<i32>,
    #[serde(rename = "workflow", skip_serializing_if = "Option::is_none")]
    pub workflow: Option<Box<models::WorkflowList200ResponseRowsInner>>,
    #[serde(rename = "concurrency", skip_serializing_if = "Option::is_none")]
    pub concurrency: Option<Box<models::WorkflowVersionGet200ResponseConcurrency>>,
    #[serde(rename = "triggers", skip_serializing_if = "Option::is_none")]
    pub triggers: Option<Box<models::WorkflowVersionGet200ResponseTriggers>>,
    #[serde(rename = "scheduleTimeout", skip_serializing_if = "Option::is_none")]
    pub schedule_timeout: Option<String>,
    #[serde(rename = "jobs", skip_serializing_if = "Option::is_none")]
    pub jobs: Option<Vec<models::WorkflowList200ResponseRowsInnerJobsInner>>,
    #[serde(rename = "workflowConfig", skip_serializing_if = "Option::is_none")]
    pub workflow_config: Option<serde_json::Value>,
}

impl WorkflowVersionGet200Response {
    pub fn new(
        metadata: models::V1TaskGet200ResponseMetadata,
        version: String,
        order: i32,
        workflow_id: String,
    ) -> WorkflowVersionGet200Response {
        WorkflowVersionGet200Response {
            metadata: Box::new(metadata),
            version,
            order,
            workflow_id,
            sticky: None,
            default_priority: None,
            workflow: None,
            concurrency: None,
            triggers: None,
            schedule_timeout: None,
            jobs: None,
            workflow_config: None,
        }
    }
}
