/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkflowGetWorkersCount200Response {
    #[serde(rename = "freeSlotCount", skip_serializing_if = "Option::is_none")]
    pub free_slot_count: Option<i32>,
    #[serde(rename = "maxSlotCount", skip_serializing_if = "Option::is_none")]
    pub max_slot_count: Option<i32>,
    #[serde(rename = "workflowRunId", skip_serializing_if = "Option::is_none")]
    pub workflow_run_id: Option<String>,
}

impl WorkflowGetWorkersCount200Response {
    pub fn new() -> WorkflowGetWorkersCount200Response {
        WorkflowGetWorkersCount200Response {
            free_slot_count: None,
            max_slot_count: None,
            workflow_run_id: None,
        }
    }
}
