/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkflowRunUpdateReplayRequest {
    #[serde(rename = "workflowRunIds")]
    pub workflow_run_ids: Vec<uuid::Uuid>,
}

impl WorkflowRunUpdateReplayRequest {
    pub fn new(workflow_run_ids: Vec<uuid::Uuid>) -> WorkflowRunUpdateReplayRequest {
        WorkflowRunUpdateReplayRequest {
            workflow_run_ids,
        }
    }
}

