/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkflowGetMetrics200Response {
    /// The number of runs for a specific group key (passed via filter)
    #[serde(rename = "groupKeyRunsCount", skip_serializing_if = "Option::is_none")]
    pub group_key_runs_count: Option<i32>,
    /// The total number of concurrency group keys.
    #[serde(rename = "groupKeyCount", skip_serializing_if = "Option::is_none")]
    pub group_key_count: Option<i32>,
}

impl WorkflowGetMetrics200Response {
    pub fn new() -> WorkflowGetMetrics200Response {
        WorkflowGetMetrics200Response {
            group_key_runs_count: None,
            group_key_count: None,
        }
    }
}

