/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkflowScheduledList200Response {
    #[serde(rename = "rows", skip_serializing_if = "Option::is_none")]
    pub rows: Option<Vec<models::ScheduledWorkflowRunCreate200Response>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<models::V1TaskEventList200ResponsePagination>>,
}

impl WorkflowScheduledList200Response {
    pub fn new() -> WorkflowScheduledList200Response {
        WorkflowScheduledList200Response {
            rows: None,
            pagination: None,
        }
    }
}

