/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkflowRunGetMetrics200Response {
    #[serde(rename = "counts", skip_serializing_if = "Option::is_none")]
    pub counts: Option<Box<models::WorkflowRunGetMetrics200ResponseCounts>>,
}

impl WorkflowRunGetMetrics200Response {
    pub fn new() -> WorkflowRunGetMetrics200Response {
        WorkflowRunGetMetrics200Response { counts: None }
    }
}
