/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkflowVersionGet200ResponseTriggersEventsInner {
    #[serde(rename = "parent_id", skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<String>,
    #[serde(rename = "event_key", skip_serializing_if = "Option::is_none")]
    pub event_key: Option<String>,
}

impl WorkflowVersionGet200ResponseTriggersEventsInner {
    pub fn new() -> WorkflowVersionGet200ResponseTriggersEventsInner {
        WorkflowVersionGet200ResponseTriggersEventsInner {
            parent_id: None,
            event_key: None,
        }
    }
}
