/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkflowUpdateRequest {
    /// Whether the workflow is paused.
    #[serde(rename = "isPaused", skip_serializing_if = "Option::is_none")]
    pub is_paused: Option<bool>,
}

impl WorkflowUpdateRequest {
    pub fn new() -> WorkflowUpdateRequest {
        WorkflowUpdateRequest {
            is_paused: None,
        }
    }
}

