/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkflowRunUpdateReplay200Response {
    #[serde(rename = "workflowRuns")]
    pub workflow_runs: Vec<models::WorkflowRunCreate200ResponseJobRunsInnerWorkflowRun>,
}

impl WorkflowRunUpdateReplay200Response {
    pub fn new(workflow_runs: Vec<models::WorkflowRunCreate200ResponseJobRunsInnerWorkflowRun>) -> WorkflowRunUpdateReplay200Response {
        WorkflowRunUpdateReplay200Response {
            workflow_runs,
        }
    }
}

