/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkerList200ResponseRowsInnerSlotsInner {
    /// The step run id.
    #[serde(rename = "stepRunId")]
    pub step_run_id: uuid::Uuid,
    /// The action id.
    #[serde(rename = "actionId")]
    pub action_id: String,
    /// The time this slot was started.
    #[serde(rename = "startedAt", skip_serializing_if = "Option::is_none")]
    pub started_at: Option<String>,
    /// The time this slot will timeout.
    #[serde(rename = "timeoutAt", skip_serializing_if = "Option::is_none")]
    pub timeout_at: Option<String>,
    /// The workflow run id.
    #[serde(rename = "workflowRunId")]
    pub workflow_run_id: uuid::Uuid,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
}

impl WorkerList200ResponseRowsInnerSlotsInner {
    pub fn new(
        step_run_id: uuid::Uuid,
        action_id: String,
        workflow_run_id: uuid::Uuid,
    ) -> WorkerList200ResponseRowsInnerSlotsInner {
        WorkerList200ResponseRowsInnerSlotsInner {
            step_run_id,
            action_id,
            started_at: None,
            timeout_at: None,
            workflow_run_id,
            status: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "PENDING")]
    Pending,
    #[serde(rename = "PENDING_ASSIGNMENT")]
    PendingAssignment,
    #[serde(rename = "ASSIGNED")]
    Assigned,
    #[serde(rename = "RUNNING")]
    Running,
    #[serde(rename = "SUCCEEDED")]
    Succeeded,
    #[serde(rename = "FAILED")]
    Failed,
    #[serde(rename = "CANCELLED")]
    Cancelled,
    #[serde(rename = "CANCELLING")]
    Cancelling,
    #[serde(rename = "BACKOFF")]
    Backoff,
}

impl Default for Status {
    fn default() -> Status {
        Self::Pending
    }
}
