/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkerList200ResponseRowsInnerRuntimeInfo {
    #[serde(rename = "sdkVersion", skip_serializing_if = "Option::is_none")]
    pub sdk_version: Option<String>,
    #[serde(rename = "language", skip_serializing_if = "Option::is_none")]
    pub language: Option<Language>,
    #[serde(rename = "languageVersion", skip_serializing_if = "Option::is_none")]
    pub language_version: Option<String>,
    #[serde(rename = "os", skip_serializing_if = "Option::is_none")]
    pub os: Option<String>,
    #[serde(rename = "runtimeExtra", skip_serializing_if = "Option::is_none")]
    pub runtime_extra: Option<String>,
}

impl WorkerList200ResponseRowsInnerRuntimeInfo {
    pub fn new() -> WorkerList200ResponseRowsInnerRuntimeInfo {
        WorkerList200ResponseRowsInnerRuntimeInfo {
            sdk_version: None,
            language: None,
            language_version: None,
            os: None,
            runtime_extra: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Language {
    #[serde(rename = "GOLANG")]
    Golang,
    #[serde(rename = "PYTHON")]
    Python,
    #[serde(rename = "TYPESCRIPT")]
    Typescript,
}

impl Default for Language {
    fn default() -> Language {
        Self::Golang
    }
}

