/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkflowVersionGet200ResponseTriggersCronsInner {
    #[serde(rename = "parent_id", skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<String>,
    #[serde(rename = "cron", skip_serializing_if = "Option::is_none")]
    pub cron: Option<String>,
}

impl WorkflowVersionGet200ResponseTriggersCronsInner {
    pub fn new() -> WorkflowVersionGet200ResponseTriggersCronsInner {
        WorkflowVersionGet200ResponseTriggersCronsInner {
            parent_id: None,
            cron: None,
        }
    }
}

