/*
 * Hatchet API
 *
 * The Hatchet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::clients::rest::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkerList200ResponseRowsInnerLabelsInner {
    #[serde(rename = "metadata")]
    pub metadata: Box<models::V1TaskGet200ResponseMetadata>,
    /// The key of the label.
    #[serde(rename = "key")]
    pub key: String,
    /// The value of the label.
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

impl WorkerList200ResponseRowsInnerLabelsInner {
    pub fn new(
        metadata: models::V1TaskGet200ResponseMetadata,
        key: String,
    ) -> WorkerList200ResponseRowsInnerLabelsInner {
        WorkerList200ResponseRowsInnerLabelsInner {
            metadata: Box::new(metadata),
            key,
            value: None,
        }
    }
}
