name: CI Checks

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
    paths:
      - src/**
      - tests/**
      - Cargo.toml
env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    name: "Check formatting"
    steps:
      - uses: actions/checkout@v5
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Run rustfmt
        run: cargo fmt --check

  unit-tests:
    runs-on: ubuntu-latest
    name: "Unit Tests"
    needs: rustfmt
    steps:
      - name: Install protoc
        run: |
          PB_REL="https://github.com/protocolbuffers/protobuf/releases"
          curl -LO $PB_REL/download/v30.2/protoc-30.2-linux-x86_64.zip
          unzip protoc-30.2-linux-x86_64.zip -d $HOME/.local
          export PATH="$PATH:$HOME/.local/bin"
      - uses: actions/checkout@v5
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Run unit tests
        run: cargo test --lib --verbose

  doc-tests:
    runs-on: ubuntu-latest
    name: "Doc Tests"
    needs: rustfmt
    steps:
      - name: Install protoc
        run: |
          PB_REL="https://github.com/protocolbuffers/protobuf/releases"
          curl -LO $PB_REL/download/v30.2/protoc-30.2-linux-x86_64.zip
          unzip protoc-30.2-linux-x86_64.zip -d $HOME/.local
          export PATH="$PATH:$HOME/.local/bin"
      - uses: actions/checkout@v5
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Run doc tests
        run: cargo test --doc --verbose

  integration-tests:
    runs-on: ubuntu-latest
    needs:
      - rustfmt
      - unit-tests
      - doc-tests
    strategy:
      fail-fast: false
      matrix:
        hatchet_version: ["v0.68.0", "v0.69.0", "v0.70.0", "v0.71.0", "latest"]
    env:
      TEST_HATCHET_LITE_VERSION: ${{ matrix.hatchet_version }}
    name: "Integration Tests - Hatchet Version: ${{ matrix.hatchet_version }}"
    steps:
      - name: Install protoc
        run: |
          PB_REL="https://github.com/protocolbuffers/protobuf/releases"
          curl -LO $PB_REL/download/v30.2/protoc-30.2-linux-x86_64.zip
          unzip protoc-30.2-linux-x86_64.zip -d $HOME/.local
          export PATH="$PATH:$HOME/.local/bin"
      - uses: actions/checkout@v5
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Run integration tests
        run: cargo test --test integration_tests --verbose
