name: Test

on:
  release:
    types:
      - published
env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    name: "Publish to crates.io"
    steps:
      - uses: actions/checkout@v5
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cargo install cargo-edit
          version=${{ github.event.release.tag_name }}
          version_no_leading_v=${version#v}
          cargo set-version $version_no_leading_v
          cargo publish
