name: Test

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        hatchet_version: ["v0.68.0", "v0.69.0", "v0.70.0", "v0.71.0", "latest"]
    env:
      TEST_HATCHET_LITE_VERSION: ${{ matrix.hatchet_version }}
    name: "Test - Hatchet Version: ${{ matrix.hatchet_version }}"
    steps:
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
      - name: Install protoc
        run: |
          PB_REL="https://github.com/protocolbuffers/protobuf/releases"
          curl -LO $PB_REL/download/v30.2/protoc-30.2-linux-x86_64.zip
          unzip protoc-30.2-linux-x86_64.zip -d $HOME/.local
          export PATH="$PATH:$HOME/.local/bin"
      - uses: actions/checkout@v4
      - name: Run tests
        run: cargo test --verbose
