name: Test

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hatchet_version: ["v0.67.0", "v0.68.0", "v0.69.0", "v0.71.0", "latest"]
    env:
      TEST_HATCHET_LITE_VERSION: ${{ matrix.hatchet_version }}
    steps:
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
      - name: Install protoc
        run: |
          DEBIAN_FRONTEND=noninteractive sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - uses: actions/checkout@v4
      - name: Run tests
        run: cargo test --verbose
